#!/usr/bin/env python3
"""
Generate Data RAM MIF from objdump -s section dump or verilog hex dump.

Usage:

  # From objdump -s output
  riscv64-unknown-elf-objdump -s -j .data elf_file | python gen_data_mif.py -o ram_init.mif

  # From verilog hex dump (generated by objcopy -O verilog)
  python gen_data_mif.py -i rv32ui-p-sb.verilog -o ram_init.mif --format verilog
"""

import argparse
import re
import sys


def parse_objdump_s(lines):
    """Parse objdump -s output to extract byte values with addresses.
    Format: " 1000 00010203 04050607 08090a0b 0c0d0e0f  ................"
    """
    data = {}
    hex_line = re.compile(
        r'^\s*([0-9a-fA-F]+)\s+'
        r'([0-9a-fA-F]{8})\s*([0-9a-fA-F]{8})?\s*([0-9a-fA-F]{8})?\s*([0-9a-fA-F]{8})?\s'
    )

    for line in lines:
        line = line.rstrip()
        m = hex_line.match(line)
        if not m:
            continue
        addr = int(m.group(1), 16)
        for gi in range(2, 6):
            group = m.group(gi)
            if group is None:
                break
            for bi in range(4):
                byte_val = (int(group, 16) >> ((3 - bi) * 8)) & 0xFF
                data[addr] = byte_val
                addr += 1

    return data


def parse_verilog_hex(lines):
    """Parse objcopy -O verilog output to extract byte values with addresses.
    Format:
        @00001000
        EF EF EF EF EF EF EF EF EF EF 00 00 00 00 00 00
    """
    data = {}
    addr = None
    byte_pat = re.compile(r'[0-9a-fA-F]{2}')

    for line in lines:
        line = line.strip()
        if not line:
            continue

        # Address marker
        if line.startswith('@'):
            addr = int(line[1:], 16)
            continue

        # Byte data line
        bytes_found = byte_pat.findall(line)
        for b in bytes_found:
            data[addr] = int(b, 16)
            addr += 1

    return data


def generate_mif(data, depth, mif_path, base_addr=0):
    """Generate a MIF file from {addr: byte} mapping.
    Only includes bytes at addresses >= base_addr."""
    # Filter by base address
    data = {a: v for a, v in data.items() if a >= base_addr}
    if not data:
        print("ERROR: No data found above base address")
        sys.exit(1)

    addr_min = min(data.keys())
    addr_max = max(data.keys())

    word_data = {}
    for addr, byte_val in data.items():
        word_addr = addr >> 2
        byte_off = addr & 0x3
        if word_addr not in word_data:
            word_data[word_addr] = 0
        word_data[word_addr] |= byte_val << (byte_off * 8)

    with open(mif_path, "w", encoding="utf-8") as f:
        f.write(f"DEPTH = {depth};\n")
        f.write("WIDTH = 32;\n")
        f.write("ADDRESS_RADIX = HEX;\n")
        f.write("DATA_RADIX = HEX;\n")
        f.write("CONTENT\n")
        f.write("BEGIN\n")

        prev_end = -1
        for waddr in sorted(word_data.keys()):
            val = word_data[waddr]
            mif_addr = waddr & (depth - 1)
            f.write(f"\t{mif_addr:04X} : {val:08X};\n")
            prev_end = mif_addr

        if prev_end + 1 < depth:
            f.write(f"\t[{prev_end + 1:04X}..{depth - 1:04X}] : 00000000;\n")

        f.write("END;\n")

    print(f"Data MIF generated: {mif_path}")
    print(f"  Byte range  : 0x{addr_min:04X} - 0x{addr_max:04X}")
    print(f"  Word range  : 0x{min(word_data.keys()):04X} - 0x{max(word_data.keys()):04X}")
    print(f"  Words init  : {len(word_data)} / {depth}")

    for waddr in sorted(word_data.keys()):
        print(f"    [{waddr:04X}] = {word_data[waddr]:08X}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate Data RAM MIF from objdump -s or verilog hex dump"
    )
    parser.add_argument("-i", "--input",
                        help="Input file. If omitted, reads from stdin.")
    parser.add_argument("-o", "--output", default="ram_init.mif",
                        help="Output MIF file path")
    parser.add_argument("--depth", type=int, default=2048,
                        help="RAM depth in words (default: 2048)")
    parser.add_argument("--base", type=lambda x: int(x, 0), default=0x1000,
                        help="Base address filter: only include bytes >= ADDR (default: 0x1000)")
    parser.add_argument("--format", choices=["objdump", "verilog"], default="verilog",
                        help="Input format: verilog (default) or objdump")
    args = parser.parse_args()

    if args.input:
        with open(args.input, "r", encoding="utf-8") as f:
            lines = f.readlines()
    else:
        lines = sys.stdin.readlines()

    if args.format == "verilog":
        data = parse_verilog_hex(lines)
    else:
        data = parse_objdump_s(lines)

    generate_mif(data, args.depth, args.output, args.base)


if __name__ == "__main__":
    main()
